name: ✨ 功能请求
description: 提议新功能或改进现有功能
title: "[Feature] "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        感谢您的功能建议！请详细描述您的需求，这将帮助我们评估和实现。

  - type: dropdown
    id: category
    attributes:
      label: 功能类别
      options:
        - 新扫描能力 (New Scan Capability)
        - 性能优化 (Performance)
        - 用户体验 (UX/CLI)
        - 输出格式 (Output Format)
        - 配置选项 (Configuration)
        - 集成/API (Integration/API)
        - 其他 (Other)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 解决什么问题？
      description: 描述您遇到的痛点或使用场景
      placeholder: |
        在进行 xxx 操作时，我希望能够...
        目前的问题是...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 期望的解决方案
      description: 描述您希望的功能或行为
      placeholder: |
        希望能够通过 -xxx 参数来...
        或者增加一个新的模块来...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 您考虑过的其他解决方案或变通方法
      placeholder: |
        目前我通过 xxx 方式来解决，但是...

  - type: dropdown
    id: priority
    attributes:
      label: 优先级建议
      description: 您认为这个功能的重要程度
      options:
        - 高 - 核心功能缺失
        - 中 - 明显改善体验
        - 低 - 锦上添花
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: 贡献意愿
      options:
        - label: 我愿意尝试实现这个功能并提交 PR
